# Generated by Django 5.1.6 on 2025-02-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pile_height', models.IntegerField()),
                ('blade_shape', models.CharField(max_length=50)),
                ('blade_material', models.CharField(max_length=50)),
                ('tuft_bind_strength', models.IntegerField()),
                ('backing_material', models.CharField(max_length=50)),
                ('warranty_length', models.IntegerField()),
                ('spec_sheet_url', models.URLField(max_length=255)),
                ('pet_friendly', models.BooleanField()),
                ('sports_field', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
