# Generated by Django 5.1.6 on 2025-02-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('turf', '0002_rename_turftypes_turftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turftype',
            name='category',
        ),
        migrations.AlterField(
            model_name='turftype',
            name='pile_height',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='turftype',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
